#!/usr/bin/env zsh
### reset-wnpr  - [CHROME] reset wn refresh page
BUILD_DIR="$(get_build_dir_)"
USER_DATA_DIR="./out/$BUILD_DIR/data"

cat "$USER_DATA_DIR/Local State" | jq '.browser.has_shown_refresh_2023_whats_new = false' > tmp.json && mv tmp.json "$USER_DATA_DIR/Local State"
