lowercaseKeywords: true
connections:
  - alias: vice
    driver: postgresql
    dbName: vice
    proto: tcp
    user: mickey
    host: localhost
    port: 5432
# example
#  - alias: individual_mysql
#    driver: mysql
#    proto: tcp
#    user: root
#    passwd: root
#    host: 127.0.0.1
#    port: 13306
#    dbName: world
#    params:
#      autocommit: "true"
#      tls: skip-verify
