#!/bin/bash
if [[ ! -e ~/bin/ranger ]]; then
  cd ~/Downloads
  wget https://ranger.github.io/ranger-stable.tar.gz
  tar xvf ranger-stable.tar.gz
  rm ranger-stable.tar.gz
  mv $(ls | grep ranger) ~/bin/ranger
  # rifle handle sql files
  echo 'ext sql = vim -- "$1"' >> ~/bin/ranger/ranger/config/rifle.conf
  echo 'ext rs = vim "$1"' >> ~/bin/ranger/ranger/config/rifle.conf
fi
