#!/bin/bash
if [[ ! -e ~/bin/ranger ]]; then
  cd ~/Downloads
  wget https://ranger.github.io/ranger-stable.tar.gz
  tar xvf ranger-stable.tar.gz
  rm ranger-stable.tar.gz
  mv $(ls | grep ranger) ~/bin/ranger
fi
