#!/bin/sh

# Usage info
show_help() {
cat << EOF
Usage: node_grep [-hs] [SEARCH_TERM]
Do grep with common options for a node project, e.g. ignore node_modules

    -h          display this help and exit
    -s          silent mode. outputs file names without modification
EOF
}

# Initialize our own variables:
# silent=false

#OPTIND=2
# Resetting OPTIND is necessary if getopts was used previously in the script.
# It is a good idea to make OPTIND local if you process options in a function.


#while getopts hvf: opt; do
#    case $opt in
#        h)
#            show_help
#            exit 0
#            ;;
#        s)  silent=true
#            ;;
#        *)
#            show_help >&2
#            exit 1
#            ;;
#    esac
#done
#shift "$((OPTIND-1))"   # Discard the options and sentinel --

# while getopts ":ht" opt; do
#   case ${opt} in
#     h ) show_help; exit 0;
#       ;;
#     s ) silent=true;
#       ;;
#     \? ) show_help >&2; exit 1;
#       ;;
#   esac
# done
# shift "$((OPTIND -1))"


# -I ignore binary
# -l filenames only
# -s silence warnings like permissions
# -r recursive
# . start on current directory including hidden files

#echo "silent\n$silent"

#do_grep() {
#}

# write this in C? - node should just be the `tree` function `grep $@ | tree`
# default is sorted with file colored? or could turn it into tree
# -c clean output
# -h help
# -r [REGEX] regex

#if $silent; then
  grep $@ . -Ilsr \
    --exclude .min.js \
    --exclude-dir build \
    --exclude-dir dist \
    --exclude-dir dist-server \
    --exclude-dir dist-client \
    --exclude-dir .fusion \
    --exclude-dir flow-typed \
    --exclude-dir node_modules \
    --exclude-dir .git \
    --exclude-dir yarn-cache \
  | sed -e 's/^\.\// - /g'
#else
#  grep $@ . -Ilsr \
#    --exclude .min.js \
#    --exclude-dir build \
#    --exclude-dir dist \
#    --exclude-dir dist-server \
#    --exclude-dir dist-client \
#    --exclude-dir .fusion \
#    --exclude-dir flow-typed \
#    --exclude-dir node_modules \
#  | sed -e 's/^\.\///g'
#fi
# End of file
