#!/bin/bash

# interactively find pr and checkout that branch
function pr-checkout() {
  get-pr-number | xargs hub pr checkout
}

# interactively find pr and open in the browser
function pr-open() {
  get-pr-number | xargs hub pr show
}

# open current branch PR in GitHub
# if no PR, open current branch in GitHub 
# doesn't work for forks
function browse() {
  local PR_URL=$(get-pr-url-for-branch)
  if [[ -n $PR_URL ]] then
    open $PR_URL
  else
    hub browse -- tree/$(get-branch-name)
  fi
}


# utility functions


# start interactive fuzzy find of current prs
# return pr number of selected pr
function get-pr-number() {
  hub pr list | fzf | awk '{print substr($1,2)}'
}

# return
# - url of open pr for current branch
# - void otherwise
function get-pr-url-for-branch() {
  hub pr list --format='%H %U%n' | awk "\$1==\"$(get-branch-name)\" {print \$2}"
}

# return name of current branch
function get-branch-name () {
  git branch 2> /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/\1/'
}
